# Generated by Django 4.2.1 on 2023-05-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_alter_boardmodel_sns_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='sns_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
